image: Visual Studio 2019
platform: "Any CPU"
configuration: Release

# before_build:
# - nuget restore

build_script:
  - cmd: pwsh .\build.ps1 %APPVEYOR_BUILD_VERSION%

after_build:
  - appveyor PushArtifact artifacts\Docker.Registry.DotNet.%APPVEYOR_BUILD_VERSION%.nupkg
